services:
  postgres:
    image: postgres:17
    container_name: idempotency-postgres

    environment:
      POSTGRES_DB: idempotency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: